# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xtc/msm8937_32go_i25/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),msm8937_32go_i25)

endif
